grails-app/domain/com/tekdays/Sponsorship.groovy
/***
 * Excerpted from "Grails 2: A Quick-Start Guide",
 * published by The Pragmatic Bookshelf.
 * Copyrights apply to this code. It may not be used to create training material, 
 * courses, books, articles, and the like. Contact us if you are in doubt.
 * We make no guarantees that this code is fit for any purpose. 
 * Visit http://www.pragmaticprogrammer.com/titles/dkgrails2 for more book information.
 ***/
package com.tekdays

class Sponsorship {
	TekEvent event
	Sponsor sponsor
	String contributionType
	String description
	String notes

	static constraints = {
		event nullable: false
		sponsor nullable: false
		contributionType inList:[
			"Other",
			"Venue",
			"A/V",
			"Promotion",
			"Cash"
		]
		description nullable: true, blank: true
		notes nullable: true, blank: true, maxSize: 5000
	}
}

grails-app/controllers/com/tekdays/SponsorshipController.groovy
package com.tekdays



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class SponsorshipController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Sponsorship.list(params), model:[sponsorshipInstanceCount: Sponsorship.count()]
    }

    def show(Sponsorship sponsorshipInstance) {
        respond sponsorshipInstance
    }

    def create() {
        respond new Sponsorship(params)
    }

    @Transactional
    def save(Sponsorship sponsorshipInstance) {
        if (sponsorshipInstance == null) {
            notFound()
            return
        }

        if (sponsorshipInstance.hasErrors()) {
            respond sponsorshipInstance.errors, view:'create'
            return
        }

        sponsorshipInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'sponsorship.label', default: 'Sponsorship'), sponsorshipInstance.id])
                redirect sponsorshipInstance
            }
            '*' { respond sponsorshipInstance, [status: CREATED] }
        }
    }

    def edit(Sponsorship sponsorshipInstance) {
        respond sponsorshipInstance
    }

    @Transactional
    def update(Sponsorship sponsorshipInstance) {
        if (sponsorshipInstance == null) {
            notFound()
            return
        }

        if (sponsorshipInstance.hasErrors()) {
            respond sponsorshipInstance.errors, view:'edit'
            return
        }

        sponsorshipInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Sponsorship.label', default: 'Sponsorship'), sponsorshipInstance.id])
                redirect sponsorshipInstance
            }
            '*'{ respond sponsorshipInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Sponsorship sponsorshipInstance) {

        if (sponsorshipInstance == null) {
            notFound()
            return
        }

        sponsorshipInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Sponsorship.label', default: 'Sponsorship'), sponsorshipInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'sponsorship.label', default: 'Sponsorship'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/sponsorship/_form.gsp
<%@ page import="com.tekdays.Sponsorship" %>



<div class="fieldcontain ${hasErrors(bean: sponsorshipInstance, field: 'event', 'error')} required">
	<label for="event">
		<g:message code="sponsorship.event.label" default="Event" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="event" name="event.id" from="${com.tekdays.TekEvent.list()}" optionKey="id" required="" value="${sponsorshipInstance?.event?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: sponsorshipInstance, field: 'sponsor', 'error')} required">
	<label for="sponsor">
		<g:message code="sponsorship.sponsor.label" default="Sponsor" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="sponsor" name="sponsor.id" from="${com.tekdays.Sponsor.list()}" optionKey="id" required="" value="${sponsorshipInstance?.sponsor?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: sponsorshipInstance, field: 'contributionType', 'error')} required">
	<label for="contributionType">
		<g:message code="sponsorship.contributionType.label" default="Contribution Type" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="contributionType" from="${sponsorshipInstance.constraints.contributionType.inList}" required="" value="${sponsorshipInstance?.contributionType}" valueMessagePrefix="sponsorship.contributionType"/>

</div>

<div class="fieldcontain ${hasErrors(bean: sponsorshipInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="sponsorship.description.label" default="Description" />
		
	</label>
	<g:textField name="description" value="${sponsorshipInstance?.description}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: sponsorshipInstance, field: 'notes', 'error')} ">
	<label for="notes">
		<g:message code="sponsorship.notes.label" default="Notes" />
		
	</label>
	<g:textArea name="notes" cols="40" rows="5" maxlength="5000" value="${sponsorshipInstance?.notes}"/>

</div>

grails-app/views/sponsorship/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'sponsorship.label', default: 'Sponsorship')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-sponsorship" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-sponsorship" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${sponsorshipInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${sponsorshipInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:sponsorshipInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/sponsorship/edit.gsp
<%@ page import="com.tekdays.Sponsorship" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'sponsorship.label', default: 'Sponsorship')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-sponsorship" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-sponsorship" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${sponsorshipInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${sponsorshipInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:sponsorshipInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${sponsorshipInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/sponsorship/index.gsp
<%@ page import="com.tekdays.Sponsorship" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'sponsorship.label', default: 'Sponsorship')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-sponsorship" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-sponsorship" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="sponsorship.event.label" default="Event" /></th>
					
						<th><g:message code="sponsorship.sponsor.label" default="Sponsor" /></th>
					
						<g:sortableColumn property="contributionType" title="${message(code: 'sponsorship.contributionType.label', default: 'Contribution Type')}" />
					
						<g:sortableColumn property="description" title="${message(code: 'sponsorship.description.label', default: 'Description')}" />
					
						<g:sortableColumn property="notes" title="${message(code: 'sponsorship.notes.label', default: 'Notes')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${sponsorshipInstanceList}" status="i" var="sponsorshipInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${sponsorshipInstance.id}">${fieldValue(bean: sponsorshipInstance, field: "event")}</g:link></td>
					
						<td>${fieldValue(bean: sponsorshipInstance, field: "sponsor")}</td>
					
						<td>${fieldValue(bean: sponsorshipInstance, field: "contributionType")}</td>
					
						<td>${fieldValue(bean: sponsorshipInstance, field: "description")}</td>
					
						<td>${fieldValue(bean: sponsorshipInstance, field: "notes")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${sponsorshipInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/sponsorship/show.gsp
<%@ page import="com.tekdays.Sponsorship" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'sponsorship.label', default: 'Sponsorship')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-sponsorship" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-sponsorship" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list sponsorship">
			
				<g:if test="${sponsorshipInstance?.event}">
				<li class="fieldcontain">
					<span id="event-label" class="property-label"><g:message code="sponsorship.event.label" default="Event" /></span>
					
						<span class="property-value" aria-labelledby="event-label"><g:link controller="tekEvent" action="show" id="${sponsorshipInstance?.event?.id}">${sponsorshipInstance?.event?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${sponsorshipInstance?.sponsor}">
				<li class="fieldcontain">
					<span id="sponsor-label" class="property-label"><g:message code="sponsorship.sponsor.label" default="Sponsor" /></span>
					
						<span class="property-value" aria-labelledby="sponsor-label"><g:link controller="sponsor" action="show" id="${sponsorshipInstance?.sponsor?.id}">${sponsorshipInstance?.sponsor?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${sponsorshipInstance?.contributionType}">
				<li class="fieldcontain">
					<span id="contributionType-label" class="property-label"><g:message code="sponsorship.contributionType.label" default="Contribution Type" /></span>
					
						<span class="property-value" aria-labelledby="contributionType-label"><g:fieldValue bean="${sponsorshipInstance}" field="contributionType"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${sponsorshipInstance?.description}">
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="sponsorship.description.label" default="Description" /></span>
					
						<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${sponsorshipInstance}" field="description"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${sponsorshipInstance?.notes}">
				<li class="fieldcontain">
					<span id="notes-label" class="property-label"><g:message code="sponsorship.notes.label" default="Notes" /></span>
					
						<span class="property-value" aria-labelledby="notes-label"><g:fieldValue bean="${sponsorshipInstance}" field="notes"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:sponsorshipInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${sponsorshipInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>